# Generated by Django 4.0.3 on 2022-07-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64)),
                ('departure_city', models.CharField(max_length=128)),
                ('departure_time', models.DateTimeField()),
                ('arrival_city', models.CharField(max_length=128)),
                ('arrival_time', models.DateTimeField()),
            ],
        ),
    ]
