# Generated by Django 4.0.3 on 2022-07-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_admin', '0003_alter_flight_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_city',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_city',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.CharField(db_index=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='flight',
            name='number',
            field=models.CharField(max_length=64),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['departure_city', 'departure_time'], name='air_admin_f_departu_5fd2b1_idx'),
        ),
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.UniqueConstraint(fields=('number', 'departure_city', 'departure_time'), name='UNIQUE_FLIGHT'),
        ),
    ]
